### ISSUE TITLE
fromAttribute bindings do not show up correctly in dependency graph

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-observable-bindings#5]
With the following element:

```js
class Person extends StacheElement {
    static props = {
        first: { type: String, bind: fromAttribute }
    };

    static view = `
        <p>Hello, {{first}}</p>
    `;
}
customElements.define("per-son", Person);
```

...and HTML:

```html
<per-son first="Kevin"></per-son>
```

I would expect the [binding](https://github.com/canjs/can-observable-bindings/blob/9c4b2f58b258b6f4d4ef5d14a170b93d0eaeff2f/src/from-attribute.js#L50-L60) to show up in the devtools dependency graph, but it does not:

![image](https://user-images.githubusercontent.com/5851984/62964404-8db3f200-bdc8-11e9-9724-7a9b7f09de82.png)

If I add an element with a binding like `<input value:bind="first">`, it is shown in the graph:

![image](https://user-images.githubusercontent.com/5851984/62964504-bfc55400-bdc8-11e9-987d-f3c5c1b83190.png)

**Comment by phillipskevin** [comment]
@justinbmeyer shouldn't `can-bind` set up the dependencies so the graph is updated to include this?

https://github.com/canjs/can-observable-bindings/blob/1748b9d94c3c8b7f8d2c6d67a7f8384709616705/src/from-attribute.js#L50-L60

Or should we have to call `canReflectDeps.addMutatedBy` manually?

**Comment by Mattchewone** [comment]
> Or should we have to call `canReflectDeps.addMutatedBy` manually?

I have tried `canReflectDeps.addMutatedBy` manually and had no success still.

**Comment by Mattchewone** [comment]
Are we going to see the attribute mutate the property for initialization? 
```js
var initializeData = stacheBindings.behaviors.initializeViewModel(bindings, props, (properties) => {
  super.initialize(properties);
  return this;
}, bindingContext);
```
The binidings get started here and the initial values are read and the properties are set, currently the initial value is not being set on the property by the binding. 

The binding will only be used for future updates.

**Comment by phillipskevin** [comment]
> Are we going to see the attribute mutate the property for initialization?

I'm not sure I understand the question, but we need to set the property from the initial value of the attribute.

**Comment by Mattchewone** [comment]
> > Are we going to see the attribute mutate the property for initialization?
> 
> I'm not sure I understand the question, but we need to set the property from the initial value of the attribute.

Sorry couldn't get my words out properly. 

What I mean to say is that if we property is being set via `super.initialize(properties)` and this isn't being done through `can-bind` would this even show up in the graph?

**Comment by phillipskevin** [comment]
If you're just setting the property by calling `initialize` manually, that wouldn't show up in the graph.

**Comment by Mattchewone** [comment]
Ok so that is going to be an issue then right?

**Comment by phillipskevin** [comment]
No? There's no dependency there. The property is just being set. Maybe I'm not understanding?
